name: FoundYou
version: '${version}'

main: pro.fazeclan.river.foundyou.FoundYou
api-version: '26.2'

authors: [ riversflowing, Sonicdude ]

dependencies:
  server:
    Jarona:
      load: BEFORE
      required: true
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true
    voicechat:
      load: BEFORE
      required: false